package dev.local.samsungalarmwidget;
import android.content.Context;import android.graphics.*;import android.os.Bundle;import android.view.*;import android.view.accessibility.AccessibilityEvent;import android.view.accessibility.AccessibilityNodeInfo;import java.util.Locale;
final class ColorPickerView extends View{
 private final Paint p=new Paint(1);private final float[] hsv=new float[3];private final boolean alphaOn;private final int initialColor;private float alpha,scale;private int active;
 ColorPickerView(Context c,int color,boolean a){super(c);initialColor=color;alphaOn=a;Color.colorToHSV(color==Color.TRANSPARENT?Color.WHITE:color,hsv);alpha=Color.alpha(color)/255f;scale=getResources().getDisplayMetrics().density;setLayerType(View.LAYER_TYPE_SOFTWARE,null);setClickable(true);setFocusable(true);updateAccessibility();}
 int getColor(){int c=Color.HSVToColor(hsv);return Color.argb(alphaOn?Math.round(alpha*255):255,Color.red(c),Color.green(c),Color.blue(c));}
 @Override protected void onDraw(Canvas c){float gap=d(10),hw=d(30),top=d(8),ah=d(22),bottom=getHeight()-d(56)-ah-d(36),right=getWidth()-hw-gap;Shader s=new LinearGradient(0,top,right,top,Color.WHITE,Color.HSVToColor(new float[]{hsv[0],1,1}),Shader.TileMode.CLAMP),v=new LinearGradient(0,top,0,bottom,Color.WHITE,Color.BLACK,Shader.TileMode.CLAMP);p.setShader(new ComposeShader(s,v,PorterDuff.Mode.MULTIPLY));c.drawRect(0,top,right,bottom,p);p.setShader(new LinearGradient(right+gap,top,right+gap,bottom,new int[]{Color.RED,Color.MAGENTA,Color.BLUE,Color.CYAN,Color.GREEN,Color.YELLOW,Color.RED},null,Shader.TileMode.CLAMP));c.drawRect(right+gap,top,getWidth(),bottom,p);p.setShader(null);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(d(2));p.setColor(Color.WHITE);c.drawCircle(hsv[1]*right,top+(1-hsv[2])*(bottom-top),d(6),p);float hy=top+(1-hsv[0]/360f)*(bottom-top);c.drawRect(right+gap-d(2),hy-d(3),getWidth()+d(2),hy+d(3),p);p.setStyle(Paint.Style.FILL);float at=bottom+d(10);p.setShader(new LinearGradient(0,at,getWidth(),at,Color.TRANSPARENT,Color.HSVToColor(hsv),Shader.TileMode.CLAMP));c.drawRect(0,at,getWidth(),at+ah,p);p.setShader(null);if(alphaOn){p.setColor(Color.WHITE);c.drawRect(alpha*getWidth()-d(2),at-d(3),alpha*getWidth()+d(2),at+ah+d(3),p);}float pt=at+ah+d(18);p.setColor(initialColor);c.drawRect(0,pt,d(58),pt+d(34),p);p.setColor(getColor());c.drawRect(d(74),pt,d(132),pt+d(34),p);p.setColor(0xFFD9D4EA);p.setTextSize(d(26));c.drawText("→",d(62),pt+d(27),p);p.setTextSize(d(17));p.setColor(0xFFF2F0F4);c.drawText(String.format("#%08X",getColor()),d(158),pt+d(25),p);}
 @Override public boolean onTouchEvent(MotionEvent e){float gap=d(10),hw=d(30),top=d(8),bottom=getHeight()-d(56)-d(22)-d(36),right=getWidth()-hw-gap;if(e.getAction()==MotionEvent.ACTION_DOWN)active=e.getY()<=bottom?(e.getX()<=right?1:2):3;if(e.getAction()==MotionEvent.ACTION_DOWN||e.getAction()==MotionEvent.ACTION_MOVE){if(active==1){hsv[1]=cl(e.getX()/right);hsv[2]=1-cl((e.getY()-top)/(bottom-top));}else if(active==2)hsv[0]=(1-cl((e.getY()-top)/(bottom-top)))*360;else if(alphaOn)alpha=cl(e.getX()/getWidth());updateAccessibility();invalidate();}if(e.getAction()==MotionEvent.ACTION_UP){performClick();sendAccessibilityEvent(AccessibilityEvent.TYPE_VIEW_SELECTED);}return true;}
 @Override public boolean performClick(){super.performClick();return true;}
 @Override public boolean onKeyDown(int keyCode,KeyEvent event){if(keyCode==KeyEvent.KEYCODE_DPAD_LEFT)return adjustHue(-5);if(keyCode==KeyEvent.KEYCODE_DPAD_RIGHT)return adjustHue(5);if(keyCode==KeyEvent.KEYCODE_DPAD_DOWN)return adjustValue(-.05f);if(keyCode==KeyEvent.KEYCODE_DPAD_UP)return adjustValue(.05f);return super.onKeyDown(keyCode,event);}
 @Override public boolean performAccessibilityAction(int action,Bundle arguments){if(action==AccessibilityNodeInfo.ACTION_SCROLL_FORWARD)return adjustHue(5);if(action==AccessibilityNodeInfo.ACTION_SCROLL_BACKWARD)return adjustHue(-5);return super.performAccessibilityAction(action,arguments);}
 @Override public void onInitializeAccessibilityNodeInfo(AccessibilityNodeInfo info){super.onInitializeAccessibilityNodeInfo(info);info.setClassName("android.widget.SeekBar");info.addAction(AccessibilityNodeInfo.AccessibilityAction.ACTION_SCROLL_FORWARD);info.addAction(AccessibilityNodeInfo.AccessibilityAction.ACTION_SCROLL_BACKWARD);}
 private boolean adjustHue(float amount){hsv[0]=(hsv[0]+amount+360)%360;changed();return true;}private boolean adjustValue(float amount){hsv[2]=cl(hsv[2]+amount);changed();return true;}private void changed(){updateAccessibility();invalidate();sendAccessibilityEvent(AccessibilityEvent.TYPE_VIEW_SELECTED);}private void updateAccessibility(){setContentDescription(getContext().getString(R.string.color_picker_value,String.format(Locale.US,"#%08X",getColor())));}
 private float cl(float x){return Math.max(0,Math.min(1,x));}private float d(float x){return x*scale;}
}
