package dev.local.samsungalarmwidget;

import android.app.*;
import android.appwidget.AppWidgetManager;
import android.content.*;
import android.content.pm.*;
import android.graphics.*;
import android.graphics.drawable.*;
import android.os.Bundle;
import android.view.*;
import android.widget.*;
import java.text.SimpleDateFormat;
import java.util.*;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

public class MainActivity extends Activity {
    private static final int BLUE=0xFF4F86F7, SURFACE=0xFF242426, TEXT=0xFFF2F0F4, SUB=0xFFC8C5CD, ICON=0xFFD0CDD5;
    private WidgetSettings settings; private ImageView preview; private LinearLayout content; private ScrollView settingsScroll; private Bitmap previewBitmap; private Long alarmMillis; private boolean subScreen; private int settingsScrollY; private ArrayList<Zone> timezoneCache; private long timezoneCacheDay=-1;
    private final ExecutorService backgroundExecutor = Executors.newSingleThreadExecutor();

    @Override protected void onCreate(Bundle state){super.onCreate(state); int id=getIntent().getIntExtra(AppWidgetManager.EXTRA_APPWIDGET_ID,AppWidgetManager.INVALID_APPWIDGET_ID); if(id!=AppWidgetManager.INVALID_APPWIDGET_ID){Intent r=new Intent();r.putExtra(AppWidgetManager.EXTRA_APPWIDGET_ID,id);setResult(RESULT_OK,r);} settings=new WidgetSettings(this);alarmMillis=settings.bool(WidgetSettings.KEY_SHOW_ALARM,true)?new AlarmStateCache(this).get():null;showSettings();}

    @Override protected void onDestroy(){backgroundExecutor.shutdownNow();if(preview!=null)preview.setImageDrawable(null);if(previewBitmap!=null&&!previewBitmap.isRecycled())previewBitmap.recycle();previewBitmap=null;super.onDestroy();}

    private void showSettings(){ subScreen=false;
        LinearLayout root=vertical(Color.BLACK); FrameLayout header=new FrameLayout(this);
        preview=new ImageView(this); preview.setScaleType(ImageView.ScaleType.FIT_XY); FrameLayout.LayoutParams pp=new FrameLayout.LayoutParams(dp(244),dp(96),Gravity.CENTER); pp.topMargin=dp(8); header.addView(preview,pp);
        root.addView(header,new LinearLayout.LayoutParams(-1,dp(291)));
        settingsScroll=new ScrollView(this);settingsScroll.setFillViewport(true);settingsScroll.setVerticalScrollBarEnabled(false);content=vertical(SURFACE);content.setPadding(0,dp(3),0,dp(30));GradientDrawable sheet=round(SURFACE,28);sheet.setCornerRadii(new float[]{dp(28),dp(28),dp(28),dp(28),0,0,0,0});content.setBackground(sheet);settingsScroll.addView(content);root.addView(settingsScroll,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);populate();refreshPreview();ScrollView scroll=settingsScroll;scroll.post(()->scroll.scrollTo(0,settingsScrollY));
    }

    private void populate(){content.removeAllViews();section("Общее");
        row("Нажмите на виджет",clickAppLabel(),R.drawable.ic_outline_touch_app,this::showAppPicker);
        colorRow("Цвет фона","Выберите цвет фона",settings.backgroundColor(),()->showColors("Цвет фона",WidgetSettings.KEY_BACKGROUND_COLOR,true));
        row("Выравнивание текста",alignmentName(),R.drawable.ic_outline_format_align_center,this::showAlignment);
        toggle("Тень от текста","Отобразить тень под текстом\nчасов",R.drawable.ic_outline_flip_to_front,WidgetSettings.KEY_SHADOW,false);
        row("Шрифт",settings.string(WidgetSettings.KEY_FONT,"Pro"),R.drawable.ic_outline_font_download,this::showFonts);
        row("Размер шрифта",settings.integer(WidgetSettings.KEY_FONT_SIZE,100)+"%",R.drawable.ic_outline_format_size,this::showFontSize);
        toggle("Отображение будильника\nили событий","Показать время следующего\nбудильника или событие\nкалендаря",R.drawable.ic_outline_alarm,WidgetSettings.KEY_SHOW_ALARM,true);
        row("Set an alarm","",R.drawable.ic_outline_alarm,this::openClock);
        section("Оформление времени");toggle("Показ времени","",R.drawable.ic_outline_access_time,WidgetSettings.KEY_SHOW_TIME,true);
        colorRow("Цвет времени","Выберите цвет часов",settings.timeColor(),()->showColors("Цвет времени",WidgetSettings.KEY_TIME_COLOR,false));
        row("Формат времени",timeFormatLabel(),R.drawable.ic_outline_font_download,this::showTimeFormat);
        row("Часовой пояс",timezoneLabel(),R.drawable.ic_outline_access_time,this::showTimezones);
        section("Оформление даты");toggle("Показ даты","",R.drawable.ic_outline_calendar_today,WidgetSettings.KEY_SHOW_DATE,false);
        colorRow("Цвет даты","Выберите цвет даты на часах",settings.dateColor(),()->showColors("Цвет даты",WidgetSettings.KEY_DATE_COLOR,false));
        row("Формат даты",WidgetRenderer.formatDate(new Date(),settings,TimeZone.getDefault()),R.drawable.ic_outline_calendar_today,this::showDateFormat);
        section("О нас");
        row(getString(R.string.app_name),"Версия "+BuildConfig.VERSION_NAME,R.drawable.ic_outline_info,null);
        row("Разработчик",getString(R.string.developer_name),R.drawable.ic_outline_info,null);
    }

    private void section(String s){TextView v=text(s,14,BLUE);v.setTypeface(Typeface.create("sans-serif-medium",0));v.setPadding(dp(20),dp(16),dp(16),dp(8));content.addView(v);}
    private void row(String a,String b,int icon,Runnable action){LinearLayout l=baseRow(a,b,icon);if(action!=null)l.setOnClickListener(v->{rememberSettingsScroll();action.run();});content.addView(l);}
    private void colorRow(String a,String b,int color,Runnable action){LinearLayout l=baseRow(a,b,R.drawable.ic_outline_color_lens);l.addView(new SettingsViews.ColorSwatch(this,color),new LinearLayout.LayoutParams(dp(32),dp(32)));l.setOnClickListener(v->action.run());content.addView(l);}
    private LinearLayout baseRow(String a,String b,int res){LinearLayout l=new LinearLayout(this);l.setGravity(Gravity.CENTER_VERTICAL);l.setPadding(dp(20),dp(8),dp(20),dp(8));boolean multiline=(a!=null&&a.contains("\n"))||(b!=null&&b.contains("\n"));l.setMinimumHeight(dp(multiline?88:72));ImageView i=new ImageView(this);i.setImageResource(res);i.setColorFilter(ICON);LinearLayout.LayoutParams ip=new LinearLayout.LayoutParams(dp(24),dp(24));ip.setMarginEnd(dp(32));l.addView(i,ip);LinearLayout labels=vertical(Color.TRANSPARENT);TextView title=text(a,16,TEXT);title.setLineSpacing(0,1f);labels.addView(title);if(b!=null&&!b.isEmpty()){TextView subtitle=text(b,14,SUB);subtitle.setLineSpacing(0,1f);labels.addView(subtitle);}l.addView(labels,new LinearLayout.LayoutParams(0,-2,1));return l;}
    private void toggle(String a,String b,int icon,String key,boolean fallback){LinearLayout l=baseRow(a,b,icon);SettingsViews.MaterialToggle t=new SettingsViews.MaterialToggle(this,settings.bool(key,fallback));t.setOnClickListener(v->{t.toggle();settings.putBoolean(key,t.isChecked());changed(WidgetSettings.KEY_SHOW_ALARM.equals(key)&&t.isChecked());});l.setOnClickListener(v->t.performClick());l.addView(t,new LinearLayout.LayoutParams(dp(52),dp(32)));content.addView(l);}

    private void showAlignment(){String[] n={"Сверху слева","Сверху","Сверху справа","Слева","По центру","Справа","Снизу слева","Снизу","Снизу справа"};choiceSheet("Выравнивание текста",n,settings.integer(WidgetSettings.KEY_ALIGNMENT,1),w->settings.putInt(WidgetSettings.KEY_ALIGNMENT,w),false);}
    private void showFonts(){String[] n={"Pro","Regular","Light","Medium","Condensed","Classic"};int s=Arrays.asList(n).indexOf(settings.string(WidgetSettings.KEY_FONT,"Pro"));choiceSheet("Шрифт",n,Math.max(s,0),w->settings.putString(WidgetSettings.KEY_FONT,n[w]),true);}
    private void showTimeFormat(){String[] n={"8:43","8:43 PM","20:43"};centerChoice("Формат времени",n,settings.integer(WidgetSettings.KEY_TIME_FORMAT,2),w->settings.putInt(WidgetSettings.KEY_TIME_FORMAT,w));}
    private interface Choice{void select(int n);}

    private void choiceSheet(String title,String[] names,int selected,Choice choice,boolean fonts){Dialog d=bottomDialog();LinearLayout box=dialogBox();box.addView(heading(title));if(!fonts)box.addView(new Space(this),new LinearLayout.LayoutParams(1,dp(16)));int rowHeight=dp(fonts?56:54);for(int x=0;x<names.length;x++){final int p=x;LinearLayout r=new LinearLayout(this);r.setGravity(Gravity.CENTER_VERTICAL);r.setPadding(dp(16),0,dp(18),0);TextView label=text(names[x],16,TEXT);if(fonts)label.setTypeface(fontFace(names[x]));r.addView(label,new LinearLayout.LayoutParams(0,rowHeight,1));if(x==selected){TextView ck=text("✓",24,0xFFD7DCEF);ck.setGravity(Gravity.CENTER);r.addView(ck,new LinearLayout.LayoutParams(dp(36),rowHeight));}r.setOnClickListener(v->{choice.select(p);d.dismiss();changed();populate();});box.addView(r);}buttons(box,d,null);d.setContentView(box);showBottom(d,fonts?-1:-2);}
    private void centerChoice(String title,String[] names,int selected,Choice choice){AlertDialog d=new AlertDialog.Builder(this).setTitle(title).setSingleChoiceItems(names,selected,(x,w)->{choice.select(w);x.dismiss();changed();populate();}).setNegativeButton("Отмена",null).create();d.setOnShowListener(x->d.getButton(-2).setTextColor(BLUE));d.show();}
    private void showFontSize(){Dialog d=bottomDialog();LinearLayout box=dialogBox();box.addView(heading("Размер шрифта"));SettingsViews.DiscreteSizeSlider s=new SettingsViews.DiscreteSizeSlider(this,settings.integer(WidgetSettings.KEY_FONT_SIZE,100));LinearLayout.LayoutParams sp=new LinearLayout.LayoutParams(-1,dp(54));sp.setMargins(dp(35),0,dp(41),0);box.addView(s,sp);buttons(box,d,()->{settings.putInt(WidgetSettings.KEY_FONT_SIZE,s.value());changed();populate();});d.setContentView(box);showBottom(d,-2);}
    private void showColors(String title,String key,boolean alpha){int start=settings.integer(key,alpha?Color.TRANSPARENT:Color.WHITE);Dialog d=bottomDialog();LinearLayout box=dialogBox();box.addView(heading(title));ColorPickerView picker=new ColorPickerView(this,start,alpha);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(alpha?392:430));p.setMargins(dp(24),0,dp(24),0);box.addView(picker,p);buttons(box,d,()->{settings.putInt(key,picker.getColor());changed();populate();});d.setContentView(box);showBottom(d,-2);}
    private Dialog bottomDialog(){Dialog d=new Dialog(this);d.requestWindowFeature(Window.FEATURE_NO_TITLE);return d;}
    private LinearLayout dialogBox(){LinearLayout b=vertical(SURFACE);b.setPadding(0,0,0,dp(8));GradientDrawable g=round(SURFACE,28);g.setCornerRadii(new float[]{dp(28),dp(28),dp(28),dp(28),0,0,0,0});b.setBackground(g);return b;}
    private TextView heading(String s){TextView h=text(s,18,TEXT);h.setTypeface(Typeface.DEFAULT_BOLD);h.setGravity(Gravity.CENTER);h.setPadding(dp(16),dp(18),dp(16),dp(18));return h;}
    private void buttons(LinearLayout box,Dialog d,Runnable ok){LinearLayout b=new LinearLayout(this);b.setGravity(Gravity.END|Gravity.CENTER_VERTICAL);b.setPadding(dp(16),dp(8),dp(24),dp(10));TextView c=button("Отмена",false);c.setOnClickListener(v->d.dismiss());b.addView(c,new LinearLayout.LayoutParams(dp(96),dp(48)));TextView y=button("OK",true);y.setOnClickListener(v->{if(ok!=null)ok.run();d.dismiss();});LinearLayout.LayoutParams yp=new LinearLayout.LayoutParams(dp(88),dp(48));yp.setMarginStart(dp(8));b.addView(y,yp);box.addView(b);}
    private TextView button(String s,boolean fill){TextView b=text(s,14,fill?0xFFDDE2F5:BLUE);b.setTypeface(Typeface.DEFAULT_BOLD);b.setGravity(Gravity.CENTER);if(fill)b.setBackground(round(0xFF46516A,28));return b;}
    private void showBottom(Dialog d,int h){d.show();Window w=d.getWindow();if(w!=null){w.setBackgroundDrawable(new ColorDrawable(Color.TRANSPARENT));w.setDimAmount(.32f);w.addFlags(WindowManager.LayoutParams.FLAG_DIM_BEHIND);w.setLayout(-1,h);w.setGravity(Gravity.BOTTOM);}}

    private void showDateFormat(){subScreen=true;LinearLayout root=screenRoot();root.addView(toolbar("Формат даты",this::showSettings));TextView sample=text(WidgetRenderer.formatDate(new Date(),settings,TimeZone.getDefault()),20,TEXT);sample.setGravity(Gravity.CENTER);sample.setTypeface(Typeface.DEFAULT_BOLD);root.addView(sample,new LinearLayout.LayoutParams(-1,dp(76)));ScrollView sc=new ScrollView(this);LinearLayout body=vertical(Color.TRANSPARENT);body.setPadding(dp(16),dp(8),dp(16),dp(12));String[] labels={"День недели","Дата","Год","День недели","Месяц","Год","Только цифры"};String[] keys={WidgetSettings.KEY_DATE_WEEKDAY,WidgetSettings.KEY_DATE_DAY,WidgetSettings.KEY_DATE_YEAR,WidgetSettings.KEY_SHORT_WEEKDAY,WidgetSettings.KEY_SHORT_MONTH,WidgetSettings.KEY_SHORT_YEAR,WidgetSettings.KEY_NUMERIC_DATE};body.addView(group("Отображать"));body.addView(checks(labels,keys,0,3));body.addView(group("Аббревиатура"));body.addView(checks(labels,keys,3,6));body.addView(group("Формат"));body.addView(checks(labels,keys,6,7));TextView adv=group("Передовой");LinearLayout.LayoutParams avp=new LinearLayout.LayoutParams(-1,-2);avp.topMargin=dp(96);body.addView(adv,avp);TextView help=text("Форматы даты и времени задаются строками шаблонов даты и времени. Полный синтаксис шаблонов даты и времени можно найти по адресу https://unicode.org/reports/tr35/tr35-dates.html",14,0xFFD6D2EA);help.setLineSpacing(dp(4),1);android.text.util.Linkify.addLinks(help,android.text.util.Linkify.WEB_URLS);help.setMovementMethod(android.text.method.LinkMovementMethod.getInstance());help.setLinkTextColor(BLUE);body.addView(help);sc.addView(body);root.addView(sc,new LinearLayout.LayoutParams(-1,0,1));LinearLayout foot=new LinearLayout(this);foot.setGravity(Gravity.END|Gravity.CENTER_VERTICAL);foot.setPadding(dp(16),0,dp(24),dp(8));TextView c=button("Отмена",false);c.setOnClickListener(v->showSettings());foot.addView(c,new LinearLayout.LayoutParams(dp(96),dp(56)));TextView ok=button("OK",true);ok.setOnClickListener(v->{changed();showSettings();});foot.addView(ok,new LinearLayout.LayoutParams(dp(88),dp(48)));root.addView(foot);setContentView(root);}
    private LinearLayout checks(String[] l,String[] k,int from,int to){LinearLayout r=new LinearLayout(this);boolean columns=to-from>1;r.setOrientation(columns?LinearLayout.HORIZONTAL:LinearLayout.VERTICAL);for(int i=from;i<to;i++){CheckBox c=new CheckBox(this);c.setText(l[i]);c.setTextSize(16);c.setTextColor(TEXT);c.setChecked(settings.bool(k[i],i<2));String key=k[i];c.setOnCheckedChangeListener((b,x)->settings.putBoolean(key,x));LinearLayout.LayoutParams p;if(columns){int column=i-from;p=column==0?new LinearLayout.LayoutParams(dp(160),dp(56)):column==1?new LinearLayout.LayoutParams(dp(88),dp(56)):new LinearLayout.LayoutParams(0,dp(56),1);}else p=new LinearLayout.LayoutParams(-1,dp(56));r.addView(c,p);}return r;}
    private TextView group(String s){TextView v=text(s,16,TEXT);v.setTypeface(Typeface.DEFAULT_BOLD);v.setPadding(0,dp(18),0,dp(8));return v;}

    private void showTimezones(){backgroundExecutor.execute(()->{ArrayList<Zone> zones=loadTimezones();runOnUiThread(()->{if(!isFinishing()&&!isDestroyed())timezoneScreen(zones);});});}
    private synchronized ArrayList<Zone> loadTimezones(){long day=System.currentTimeMillis()/86_400_000L;if(timezoneCache!=null&&timezoneCacheDay==day)return timezoneCache;ArrayList<Zone> zones=new ArrayList<>();zones.add(new Zone("auto","Автоматически",""));Date now=new Date();for(String id:TimeZone.getAvailableIDs()){TimeZone z=TimeZone.getTimeZone(id);int m=z.getOffset(now.getTime())/60000;String off=String.format(Locale.US,"UTC%s%d%s",m<0?"−":"+",Math.abs(m)/60,Math.abs(m)%60==0?"":String.format(Locale.US,":%02d",Math.abs(m)%60));zones.add(new Zone(id,id.substring(id.lastIndexOf('/')+1).replace('_',' '),off));}Collections.sort(zones.subList(1,zones.size()),Comparator.comparingInt((Zone z)->TimeZone.getTimeZone(z.id).getOffset(now.getTime())).thenComparing(z->z.name));timezoneCache=zones;timezoneCacheDay=day;return zones;}
    private void timezoneScreen(ArrayList<Zone> zones){subScreen=true;LinearLayout root=screenRoot();root.addView(toolbar("Часовой пояс",this::showSettings));ListView list=new ListView(this);list.setDivider(null);list.setAdapter(new PickerAdapters.TimezoneAdapter(this,zones,settings.string(WidgetSettings.KEY_TIMEZONE,"auto")));list.setOnItemClickListener((a,v,p,id)->{settings.putString(WidgetSettings.KEY_TIMEZONE,zones.get(p).id);changed();showSettings();});root.addView(list,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);}

    private void showAppPicker(){backgroundExecutor.execute(()->{PackageManager pm=getPackageManager();List<ResolveInfo> apps=pm.queryIntentActivities(new Intent(Intent.ACTION_MAIN).addCategory(Intent.CATEGORY_LAUNCHER),0);Collections.sort(apps,Comparator.comparing(a->a.loadLabel(pm).toString(),String.CASE_INSENSITIVE_ORDER));List<ResolveInfo> shortcuts=pm.queryIntentActivities(new Intent(Intent.ACTION_CREATE_SHORTCUT),0);runOnUiThread(()->{if(!isFinishing()&&!isDestroyed())appScreen(pm,apps,shortcuts);});});}
    private void appScreen(PackageManager pm,List<ResolveInfo> apps,List<ResolveInfo> shortcuts){subScreen=true;LinearLayout root=screenRoot();root.addView(toolbar("Нажмите на виджет",this::showSettings));LinearLayout tabs=new LinearLayout(this);TextView a=tab("Приложения",true),s=tab("Ярлыки",false);tabs.addView(a,new LinearLayout.LayoutParams(0,dp(56),1));tabs.addView(s,new LinearLayout.LayoutParams(0,dp(56),1));root.addView(tabs);FrameLayout host=new FrameLayout(this);root.addView(host,new LinearLayout.LayoutParams(-1,0,1));Runnable showA=()->{a.setTextColor(BLUE);s.setTextColor(TEXT);pickerList(host,pm,apps,false);};Runnable showS=()->{a.setTextColor(TEXT);s.setTextColor(BLUE);pickerList(host,pm,shortcuts,true);};a.setOnClickListener(v->showA.run());s.setOnClickListener(v->showS.run());showA.run();setContentView(root);}
    private void pickerList(FrameLayout host,PackageManager pm,List<ResolveInfo> in,boolean shortcuts){ArrayList<ResolveInfo> items=new ArrayList<>(in);ListView list=new ListView(this);list.setDivider(null);list.setAdapter(new PickerAdapters.AppAdapter(this,pm,items,shortcuts));list.setOnItemClickListener((x,v,p,id)->{if(!shortcuts&&p==0)settings.putString(WidgetSettings.KEY_CLICK_PACKAGE,"");else if(!shortcuts&&p==1)settings.putString(WidgetSettings.KEY_CLICK_PACKAGE,"com.sec.android.app.clockpackage");else settings.putString(WidgetSettings.KEY_CLICK_PACKAGE,items.get(p-(shortcuts?0:2)).activityInfo.packageName);changed();showSettings();});host.removeAllViews();host.addView(list);}
    private TextView tab(String s,boolean on){TextView t=text(s,14,on?BLUE:TEXT);t.setTypeface(Typeface.DEFAULT_BOLD);t.setGravity(Gravity.CENTER);return t;}
    private LinearLayout screenRoot(){LinearLayout root=vertical(0xFF171719);root.setPadding(0,dp(32),0,0);return root;}
    private View toolbar(String title,Runnable back){LinearLayout b=new LinearLayout(this);b.setGravity(Gravity.CENTER_VERTICAL);b.setPadding(dp(12),0,dp(16),0);ImageView arrow=new ImageView(this);arrow.setImageResource(R.drawable.ic_arrow_back);arrow.setPadding(dp(10),dp(10),dp(10),dp(10));arrow.setOnClickListener(v->back.run());b.addView(arrow,new LinearLayout.LayoutParams(dp(44),dp(64)));TextView t=text(title,22,TEXT);t.setGravity(Gravity.CENTER_VERTICAL);t.setPadding(dp(4),0,0,0);b.addView(t,new LinearLayout.LayoutParams(0,dp(64),1));return b;}
    @Override public void onBackPressed(){if(subScreen)showSettings();else super.onBackPressed();}

    private void openClock(){Intent i=getPackageManager().getLaunchIntentForPackage("com.sec.android.app.clockpackage");if(i!=null)startActivity(i);}
    private String alignmentName(){return new String[]{"Сверху слева","Сверху","Сверху справа","Слева","По центру","Справа","Снизу слева","Снизу","Снизу справа"}[settings.integer(WidgetSettings.KEY_ALIGNMENT,1)];}
    private String timeFormatLabel(){int x=settings.integer(WidgetSettings.KEY_TIME_FORMAT,2);return new SimpleDateFormat(new String[]{"h:mm","h:mm a","HH:mm"}[x],Locale.getDefault()).format(new Date());}
    private String timezoneLabel(){String z=settings.string(WidgetSettings.KEY_TIMEZONE,"auto");return "auto".equals(z)?"Автоматически":z.substring(z.lastIndexOf('/')+1).replace('_',' ');}
    private String clickAppLabel(){String p=settings.string(WidgetSettings.KEY_CLICK_PACKAGE,"com.sec.android.app.clockpackage");if(p.isEmpty())return "Ничего не делать";try{return getPackageManager().getApplicationLabel(getPackageManager().getApplicationInfo(p,0)).toString();}catch(Exception e){return p;}}
    private Typeface fontFace(String n){if(n.equals("Light"))return Typeface.create("sans-serif-light",0);if(n.equals("Medium"))return Typeface.create("sans-serif-medium",0);if(n.equals("Condensed"))return Typeface.create("sans-serif-condensed",0);if(n.equals("Classic"))return Typeface.SERIF;return Typeface.create("sans-serif",0);}
    private void rememberSettingsScroll(){if(settingsScroll!=null)settingsScrollY=settingsScroll.getScrollY();}
    private void changed(){changed(false);}
    private void changed(boolean refreshAlarm){alarmMillis=settings.bool(WidgetSettings.KEY_SHOW_ALARM,true)?new AlarmStateCache(this).get():null;refreshPreview();AlarmWidgetProvider.requestUpdate(getApplicationContext(),refreshAlarm);}
    private void refreshPreview(){if(preview==null)return;Bitmap next=WidgetRenderer.render(this,214,84,alarmMillis);Bitmap previous=previewBitmap;previewBitmap=next;preview.setImageBitmap(next);if(previous!=null&&previous!=next&&!previous.isRecycled())previous.recycle();}
    private LinearLayout vertical(int color){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setBackgroundColor(color);return l;}
    private TextView text(String s,float size,int color){TextView v=new TextView(this);v.setText(s);v.setTextSize(size);v.setTextColor(color);return v;}
    private GradientDrawable round(int color,int radius){GradientDrawable g=new GradientDrawable();g.setColor(color);g.setCornerRadius(dp(radius));return g;}
    private int dp(int x){return Math.round(x*getResources().getDisplayMetrics().density);}
    static final class Zone{final String id,name,offset;Zone(String i,String n,String o){id=i;name=n;offset=o;}}
}
