package dev.local.samsungalarmwidget;

import android.annotation.SuppressLint;
import android.app.*;
import android.appwidget.AppWidgetManager;
import android.content.*;
import android.content.pm.*;
import android.graphics.*;
import android.graphics.drawable.*;
import android.net.Uri;
import android.os.Bundle;
import android.os.Build;
import android.os.Process;
import android.view.*;
import android.widget.*;
import android.window.OnBackInvokedDispatcher;
import java.text.SimpleDateFormat;
import java.util.*;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

public class MainActivity extends Activity {
    private static final int BLUE=0xFF5289FA, SURFACE=0xFF242426, TEXT=0xFFF2F0F4, SUB=0xFFC8C5CD, ICON=0xFFD0CDD5;
    private WidgetSettings settings; private ImageView preview; private LinearLayout content; private ScrollView settingsScroll; private Bitmap previewBitmap; private Long alarmMillis; private boolean subScreen; private int settingsScrollY; private ArrayList<Zone> timezoneCache; private long timezoneCacheDay=-1;
    private final ExecutorService backgroundExecutor = Executors.newSingleThreadExecutor();

    @Override protected void onCreate(Bundle state){super.onCreate(state);if(Build.VERSION.SDK_INT>=Build.VERSION_CODES.TIRAMISU)getOnBackInvokedDispatcher().registerOnBackInvokedCallback(OnBackInvokedDispatcher.PRIORITY_DEFAULT,this::handleBack); int id=getIntent().getIntExtra(AppWidgetManager.EXTRA_APPWIDGET_ID,AppWidgetManager.INVALID_APPWIDGET_ID); if(id!=AppWidgetManager.INVALID_APPWIDGET_ID){Intent r=new Intent();r.putExtra(AppWidgetManager.EXTRA_APPWIDGET_ID,id);setResult(RESULT_OK,r);} settings=new WidgetSettings(this);alarmMillis=settings.bool(WidgetSettings.KEY_SHOW_ALARM,true)?new AlarmStateCache(this).get():null;showSettings();}

    @Override protected void onDestroy(){backgroundExecutor.shutdownNow();if(preview!=null)preview.setImageDrawable(null);if(previewBitmap!=null&&!previewBitmap.isRecycled())previewBitmap.recycle();previewBitmap=null;super.onDestroy();}

    private void showSettings(){ subScreen=false;
        LinearLayout root=vertical(Color.BLACK); FrameLayout header=new FrameLayout(this);
        preview=new ImageView(this); preview.setScaleType(ImageView.ScaleType.FIT_XY);preview.setContentDescription(getString(R.string.widget_description)); FrameLayout.LayoutParams pp=new FrameLayout.LayoutParams(dp(244),dp(96),Gravity.CENTER); pp.topMargin=dp(8); header.addView(preview,pp);
        root.addView(header,new LinearLayout.LayoutParams(-1,dp(291)));
        settingsScroll=new ScrollView(this);settingsScroll.setFillViewport(true);settingsScroll.setVerticalScrollBarEnabled(false);content=vertical(SURFACE);content.setPadding(0,dp(3),0,dp(30));GradientDrawable sheet=round(SURFACE,28);sheet.setCornerRadii(new float[]{dp(28),dp(28),dp(28),dp(28),0,0,0,0});content.setBackground(sheet);settingsScroll.addView(content);root.addView(settingsScroll,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);populate();refreshPreview();ScrollView scroll=settingsScroll;scroll.post(()->scroll.scrollTo(0,settingsScrollY));
    }

    private void populate(){content.removeAllViews();section(getString(R.string.section_general));
        row(getString(R.string.tap_widget),clickAppLabel(),R.drawable.ic_outline_touch_app,this::showAppPicker);
        colorRow(getString(R.string.background_color),getString(R.string.choose_background_color),settings.backgroundColor(),()->showColors(getString(R.string.background_color),WidgetSettings.KEY_BACKGROUND_COLOR,true));
        row(getString(R.string.text_alignment),alignmentName(),R.drawable.ic_outline_format_align_center,this::showAlignment);
        toggle(getString(R.string.text_shadow),getString(R.string.text_shadow_summary),R.drawable.ic_outline_flip_to_front,WidgetSettings.KEY_SHADOW,false);
        row(getString(R.string.font),settings.string(WidgetSettings.KEY_FONT,"Pro"),R.drawable.ic_outline_font_download,this::showFonts);
        row(getString(R.string.font_size),getString(R.string.percent_value,settings.integer(WidgetSettings.KEY_FONT_SIZE,100)),R.drawable.ic_outline_format_size,this::showFontSize);
        toggle(getString(R.string.show_alarm),getString(R.string.show_alarm_summary),R.drawable.ic_outline_alarm,WidgetSettings.KEY_SHOW_ALARM,true);
        row(getString(R.string.set_alarm),"",R.drawable.ic_outline_alarm,this::openClock);
        section(getString(R.string.section_time));toggle(getString(R.string.show_time),"",R.drawable.ic_outline_access_time,WidgetSettings.KEY_SHOW_TIME,true);
        colorRow(getString(R.string.time_color),getString(R.string.choose_time_color),settings.timeColor(),()->showColors(getString(R.string.time_color),WidgetSettings.KEY_TIME_COLOR,false));
        row(getString(R.string.time_format),timeFormatLabel(),R.drawable.ic_outline_font_download,this::showTimeFormat);
        row(getString(R.string.time_zone),timezoneLabel(),R.drawable.ic_outline_access_time,this::showTimezones);
        section(getString(R.string.section_date));toggle(getString(R.string.show_date),"",R.drawable.ic_outline_calendar_today,WidgetSettings.KEY_SHOW_DATE,false);
        colorRow(getString(R.string.date_color),getString(R.string.choose_date_color),settings.dateColor(),()->showColors(getString(R.string.date_color),WidgetSettings.KEY_DATE_COLOR,false));
        row(getString(R.string.date_format),WidgetRenderer.formatDate(new Date(),settings,TimeZone.getDefault()),R.drawable.ic_outline_calendar_today,this::showDateFormat);
        section(getString(R.string.section_permissions));
        if(hasRequiredPermissions()) {
            row(getString(R.string.permissions_ready),getString(R.string.check_permissions_summary),R.drawable.ic_outline_info,this::showPermissionStatus);
        } else {
            row(getString(R.string.permissions_missing),getString(R.string.permissions_missing_summary),R.drawable.ic_outline_info,this::showPermissionInstructions);
            row(getString(R.string.check_permissions),getString(R.string.check_permissions_summary),R.drawable.ic_outline_info,this::showPermissionStatus);
        }
        section(getString(R.string.section_about));
        row(getString(R.string.about_legal),getString(R.string.about_legal_summary),R.drawable.ic_outline_info,this::showAbout);
    }

    private void section(String s){TextView v=text(s,14,BLUE);v.setTypeface(Typeface.create("sans-serif-medium",Typeface.NORMAL));v.setPadding(dp(20),dp(16),dp(16),dp(8));content.addView(v);}
    private void row(String a,String b,int icon,Runnable action){LinearLayout l=baseRow(a,b,icon);if(action!=null){l.setClickable(true);l.setFocusable(true);l.setOnClickListener(v->{rememberSettingsScroll();action.run();});}content.addView(l);}
    private void colorRow(String a,String b,int color,Runnable action){LinearLayout l=baseRow(a,b,R.drawable.ic_outline_color_lens);SettingsViews.ColorSwatch swatch=new SettingsViews.ColorSwatch(this,color);swatch.setContentDescription(getString(R.string.color_value,String.format(Locale.US,"#%08X",color)));l.addView(swatch,new LinearLayout.LayoutParams(dp(32),dp(32)));l.setClickable(true);l.setFocusable(true);l.setOnClickListener(v->action.run());content.addView(l);}
    private LinearLayout baseRow(String a,String b,int res){LinearLayout l=new LinearLayout(this);l.setGravity(Gravity.CENTER_VERTICAL);l.setPadding(dp(20),dp(12),dp(20),dp(12));l.setMinimumHeight(dp(72));ImageView i=new ImageView(this);i.setImageResource(res);i.setColorFilter(ICON);i.setImportantForAccessibility(View.IMPORTANT_FOR_ACCESSIBILITY_NO);LinearLayout.LayoutParams ip=new LinearLayout.LayoutParams(dp(24),dp(24));ip.setMarginEnd(dp(32));l.addView(i,ip);LinearLayout labels=vertical(Color.TRANSPARENT);TextView title=text(a,16,TEXT);title.setLineSpacing(0,1.05f);labels.addView(title);if(b!=null&&!b.isEmpty()){TextView subtitle=text(b,14,SUB);subtitle.setLineSpacing(0,1.1f);labels.addView(subtitle);}l.addView(labels,new LinearLayout.LayoutParams(0,-2,1));return l;}
    private void toggle(String a,String b,int icon,String key,boolean fallback){LinearLayout l=baseRow(a,b,icon);SettingsViews.MaterialToggle t=new SettingsViews.MaterialToggle(this,settings.bool(key,fallback));t.setContentDescription(a);t.setOnClickListener(v->{t.toggle();settings.putBoolean(key,t.isChecked());changed(WidgetSettings.KEY_SHOW_ALARM.equals(key)&&t.isChecked());});l.setClickable(true);l.setFocusable(true);l.setOnClickListener(v->t.performClick());l.addView(t,new LinearLayout.LayoutParams(dp(52),dp(32)));content.addView(l);}

    private void showAlignment(){String[] n=getResources().getStringArray(R.array.alignment_names);choiceSheet(getString(R.string.text_alignment),n,settings.integer(WidgetSettings.KEY_ALIGNMENT,1),w->settings.putInt(WidgetSettings.KEY_ALIGNMENT,w),false);}
    private void showFonts(){String[] n=getResources().getStringArray(R.array.font_names);int s=Arrays.asList(n).indexOf(settings.string(WidgetSettings.KEY_FONT,"Pro"));choiceSheet(getString(R.string.font),n,Math.max(s,0),w->settings.putString(WidgetSettings.KEY_FONT,n[w]),true);}
    private void showTimeFormat(){String[] n=getResources().getStringArray(R.array.time_format_examples);centerChoice(getString(R.string.time_format),n,settings.integer(WidgetSettings.KEY_TIME_FORMAT,2),w->settings.putInt(WidgetSettings.KEY_TIME_FORMAT,w));}
    private interface Choice{void select(int n);}

    private void choiceSheet(String title,String[] names,int selected,Choice choice,boolean fonts){Dialog d=bottomDialog();LinearLayout box=dialogBox();box.addView(heading(title));if(!fonts)box.addView(new Space(this),new LinearLayout.LayoutParams(1,dp(16)));for(int x=0;x<names.length;x++){final int p=x;LinearLayout r=new LinearLayout(this);r.setGravity(Gravity.CENTER_VERTICAL);r.setPadding(dp(16),dp(8),dp(18),dp(8));r.setMinimumHeight(dp(fonts?56:54));r.setClickable(true);r.setFocusable(true);TextView label=text(names[x],16,TEXT);if(fonts)label.setTypeface(fontFace(names[x]));r.addView(label,new LinearLayout.LayoutParams(0,-2,1));if(x==selected){TextView ck=text("✓",24,0xFFD7DCEF);ck.setGravity(Gravity.CENTER);ck.setContentDescription(getString(R.string.selected));r.addView(ck,new LinearLayout.LayoutParams(dp(36),-2));}r.setOnClickListener(v->{choice.select(p);d.dismiss();changed();populate();});box.addView(r);}buttons(box,d,null);d.setContentView(box);showBottom(d,fonts?-1:-2);}
    private void centerChoice(String title,String[] names,int selected,Choice choice){AlertDialog d=new AlertDialog.Builder(this).setTitle(title).setSingleChoiceItems(names,selected,(x,w)->{choice.select(w);x.dismiss();changed();populate();}).setNegativeButton(R.string.cancel,null).create();d.setOnShowListener(x->d.getButton(-2).setTextColor(BLUE));d.show();}
    private void showFontSize(){Dialog d=bottomDialog();LinearLayout box=dialogBox();box.addView(heading(getString(R.string.font_size)));SettingsViews.DiscreteSizeSlider s=new SettingsViews.DiscreteSizeSlider(this,settings.integer(WidgetSettings.KEY_FONT_SIZE,100));LinearLayout.LayoutParams sp=new LinearLayout.LayoutParams(-1,dp(54));sp.setMargins(dp(35),0,dp(41),0);box.addView(s,sp);buttons(box,d,()->{settings.putInt(WidgetSettings.KEY_FONT_SIZE,s.value());changed();populate();});d.setContentView(box);showBottom(d,-2);}
    private void showColors(String title,String key,boolean alpha){int start=settings.integer(key,alpha?Color.TRANSPARENT:Color.WHITE);Dialog d=bottomDialog();LinearLayout box=dialogBox();box.addView(heading(title));ColorPickerView picker=new ColorPickerView(this,start,alpha);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(alpha?392:430));p.setMargins(dp(24),0,dp(24),0);box.addView(picker,p);buttons(box,d,()->{settings.putInt(key,picker.getColor());changed();populate();});d.setContentView(box);showBottom(d,-2);}
    private Dialog bottomDialog(){Dialog d=new Dialog(this);d.requestWindowFeature(Window.FEATURE_NO_TITLE);return d;}
    private LinearLayout dialogBox(){LinearLayout b=vertical(SURFACE);b.setPadding(0,0,0,dp(8));GradientDrawable g=round(SURFACE,28);g.setCornerRadii(new float[]{dp(28),dp(28),dp(28),dp(28),0,0,0,0});b.setBackground(g);return b;}
    private TextView heading(String s){TextView h=text(s,18,TEXT);h.setTypeface(Typeface.DEFAULT_BOLD);h.setGravity(Gravity.CENTER);h.setPadding(dp(16),dp(18),dp(16),dp(18));return h;}
    private void buttons(LinearLayout box,Dialog d,Runnable ok){LinearLayout b=new LinearLayout(this);b.setGravity(Gravity.END|Gravity.CENTER_VERTICAL);b.setPadding(dp(16),dp(8),dp(24),dp(10));TextView c=button(getString(R.string.cancel),false);c.setOnClickListener(v->d.dismiss());b.addView(c,new LinearLayout.LayoutParams(dp(112),-2));TextView y=button(getString(R.string.ok),true);y.setOnClickListener(v->{if(ok!=null)ok.run();d.dismiss();});LinearLayout.LayoutParams yp=new LinearLayout.LayoutParams(dp(96),-2);yp.setMarginStart(dp(8));b.addView(y,yp);box.addView(b);}
    private TextView button(String s,boolean fill){TextView b=text(s,14,fill?0xFFFFFFFF:BLUE);b.setTypeface(Typeface.DEFAULT_BOLD);b.setGravity(Gravity.CENTER);b.setMinHeight(dp(48));b.setPadding(dp(12),dp(8),dp(12),dp(8));b.setClickable(true);b.setFocusable(true);if(fill)b.setBackground(round(0xFF46516A,28));return b;}
    private void showBottom(Dialog d,int h){d.show();Window w=d.getWindow();if(w!=null){w.setBackgroundDrawable(new ColorDrawable(Color.TRANSPARENT));w.setDimAmount(.32f);w.addFlags(WindowManager.LayoutParams.FLAG_DIM_BEHIND);w.setLayout(-1,h);w.setGravity(Gravity.BOTTOM);}}

    private void showDateFormat(){subScreen=true;LinearLayout root=screenRoot();root.addView(toolbar(getString(R.string.date_format),this::showSettings));TextView sample=text(WidgetRenderer.formatDate(new Date(),settings,TimeZone.getDefault()),20,TEXT);sample.setGravity(Gravity.CENTER);sample.setTypeface(Typeface.DEFAULT_BOLD);sample.setPadding(dp(12),dp(12),dp(12),dp(12));sample.setMinHeight(dp(76));root.addView(sample,new LinearLayout.LayoutParams(-1,-2));ScrollView sc=new ScrollView(this);LinearLayout body=vertical(Color.TRANSPARENT);body.setPadding(dp(16),dp(8),dp(16),dp(12));String[] labels={getString(R.string.date_weekday),getString(R.string.date_day),getString(R.string.date_year),getString(R.string.date_weekday),getString(R.string.date_month),getString(R.string.date_year),getString(R.string.date_numbers_only)};String[] keys={WidgetSettings.KEY_DATE_WEEKDAY,WidgetSettings.KEY_DATE_DAY,WidgetSettings.KEY_DATE_YEAR,WidgetSettings.KEY_SHORT_WEEKDAY,WidgetSettings.KEY_SHORT_MONTH,WidgetSettings.KEY_SHORT_YEAR,WidgetSettings.KEY_NUMERIC_DATE};body.addView(group(getString(R.string.date_show)));body.addView(checks(labels,keys,0,3));body.addView(group(getString(R.string.date_abbreviation)));body.addView(checks(labels,keys,3,6));body.addView(group(getString(R.string.date_format_group)));body.addView(checks(labels,keys,6,7));TextView adv=group(getString(R.string.date_advanced));LinearLayout.LayoutParams avp=new LinearLayout.LayoutParams(-1,-2);avp.topMargin=dp(48);body.addView(adv,avp);TextView help=text(getString(R.string.date_pattern_help),14,0xFFD6D2EA);help.setLineSpacing(dp(4),1);android.text.util.Linkify.addLinks(help,android.text.util.Linkify.WEB_URLS);help.setMovementMethod(android.text.method.LinkMovementMethod.getInstance());help.setLinkTextColor(BLUE);body.addView(help);sc.addView(body);root.addView(sc,new LinearLayout.LayoutParams(-1,0,1));LinearLayout foot=new LinearLayout(this);foot.setGravity(Gravity.END|Gravity.CENTER_VERTICAL);foot.setPadding(dp(16),dp(8),dp(24),dp(8));TextView c=button(getString(R.string.cancel),false);c.setOnClickListener(v->showSettings());foot.addView(c,new LinearLayout.LayoutParams(dp(112),-2));TextView ok=button(getString(R.string.ok),true);ok.setOnClickListener(v->{changed();showSettings();});foot.addView(ok,new LinearLayout.LayoutParams(dp(96),-2));root.addView(foot);setContentView(root);}
    private LinearLayout checks(String[] l,String[] k,int from,int to){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);for(int i=from;i<to;i++){CheckBox c=new CheckBox(this);c.setText(l[i]);c.setTextSize(16);c.setTextColor(TEXT);c.setMinHeight(dp(48));c.setChecked(settings.bool(k[i],i<2));String key=k[i];c.setOnCheckedChangeListener((b,x)->settings.putBoolean(key,x));r.addView(c,new LinearLayout.LayoutParams(-1,-2));}return r;}
    private TextView group(String s){TextView v=text(s,16,TEXT);v.setTypeface(Typeface.DEFAULT_BOLD);v.setPadding(0,dp(18),0,dp(8));return v;}

    private void showTimezones(){backgroundExecutor.execute(()->{ArrayList<Zone> zones=loadTimezones();runOnUiThread(()->{if(!isFinishing()&&!isDestroyed())timezoneScreen(zones);});});}
    private synchronized ArrayList<Zone> loadTimezones(){long day=System.currentTimeMillis()/86_400_000L;if(timezoneCache!=null&&timezoneCacheDay==day)return timezoneCache;ArrayList<Zone> zones=new ArrayList<>();zones.add(new Zone("auto",getString(R.string.automatic),""));Date now=new Date();for(String id:TimeZone.getAvailableIDs()){TimeZone z=TimeZone.getTimeZone(id);int m=z.getOffset(now.getTime())/60000;String off=String.format(Locale.US,"UTC%s%d%s",m<0?"−":"+",Math.abs(m)/60,Math.abs(m)%60==0?"":String.format(Locale.US,":%02d",Math.abs(m)%60));zones.add(new Zone(id,id.substring(id.lastIndexOf('/')+1).replace('_',' '),off));}Collections.sort(zones.subList(1,zones.size()),Comparator.comparingInt((Zone z)->TimeZone.getTimeZone(z.id).getOffset(now.getTime())).thenComparing(z->z.name));timezoneCache=zones;timezoneCacheDay=day;return zones;}
    private void timezoneScreen(ArrayList<Zone> zones){subScreen=true;LinearLayout root=screenRoot();root.addView(toolbar(getString(R.string.time_zone),this::showSettings));ListView list=new ListView(this);list.setDivider(null);list.setAdapter(new PickerAdapters.TimezoneAdapter(this,zones,settings.string(WidgetSettings.KEY_TIMEZONE,"auto")));list.setOnItemClickListener((a,v,p,id)->{settings.putString(WidgetSettings.KEY_TIMEZONE,zones.get(p).id);changed();showSettings();});root.addView(list,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);}

    private void showAppPicker(){backgroundExecutor.execute(()->{PackageManager pm=getPackageManager();List<ResolveInfo> apps=pm.queryIntentActivities(new Intent(Intent.ACTION_MAIN).addCategory(Intent.CATEGORY_LAUNCHER),0);Collections.sort(apps,Comparator.comparing(a->a.loadLabel(pm).toString(),String.CASE_INSENSITIVE_ORDER));List<ResolveInfo> shortcuts=pm.queryIntentActivities(new Intent(Intent.ACTION_CREATE_SHORTCUT),0);runOnUiThread(()->{if(!isFinishing()&&!isDestroyed())appScreen(pm,apps,shortcuts);});});}
    private void appScreen(PackageManager pm,List<ResolveInfo> apps,List<ResolveInfo> shortcuts){subScreen=true;LinearLayout root=screenRoot();root.addView(toolbar(getString(R.string.tap_widget),this::showSettings));LinearLayout tabs=new LinearLayout(this);TextView a=tab(getString(R.string.applications),true),s=tab(getString(R.string.shortcuts),false);tabs.addView(a,new LinearLayout.LayoutParams(0,dp(56),1));tabs.addView(s,new LinearLayout.LayoutParams(0,dp(56),1));root.addView(tabs);FrameLayout host=new FrameLayout(this);root.addView(host,new LinearLayout.LayoutParams(-1,0,1));Runnable showA=()->{a.setTextColor(BLUE);s.setTextColor(TEXT);pickerList(host,pm,apps,false);};Runnable showS=()->{a.setTextColor(TEXT);s.setTextColor(BLUE);pickerList(host,pm,shortcuts,true);};a.setOnClickListener(v->showA.run());s.setOnClickListener(v->showS.run());showA.run();setContentView(root);}
    private void pickerList(FrameLayout host,PackageManager pm,List<ResolveInfo> in,boolean shortcuts){ArrayList<ResolveInfo> items=new ArrayList<>(in);ListView list=new ListView(this);list.setDivider(null);list.setAdapter(new PickerAdapters.AppAdapter(this,pm,items,shortcuts));list.setOnItemClickListener((x,v,p,id)->{if(!shortcuts&&p==0)settings.putString(WidgetSettings.KEY_CLICK_PACKAGE,"");else if(!shortcuts&&p==1)settings.putString(WidgetSettings.KEY_CLICK_PACKAGE,"com.sec.android.app.clockpackage");else settings.putString(WidgetSettings.KEY_CLICK_PACKAGE,items.get(p-(shortcuts?0:2)).activityInfo.packageName);changed();showSettings();});host.removeAllViews();host.addView(list);}
    private TextView tab(String s,boolean on){TextView t=text(s,14,on?BLUE:TEXT);t.setTypeface(Typeface.DEFAULT_BOLD);t.setGravity(Gravity.CENTER);t.setClickable(true);t.setFocusable(true);return t;}
    private LinearLayout screenRoot(){LinearLayout root=vertical(0xFF171719);root.setPadding(0,dp(32),0,0);return root;}
    private View toolbar(String title,Runnable back){LinearLayout b=new LinearLayout(this);b.setGravity(Gravity.CENTER_VERTICAL);b.setPadding(dp(12),0,dp(16),0);ImageView arrow=new ImageView(this);arrow.setImageResource(R.drawable.ic_arrow_back);arrow.setPadding(dp(10),dp(10),dp(10),dp(10));arrow.setContentDescription(getString(R.string.back));arrow.setClickable(true);arrow.setFocusable(true);arrow.setOnClickListener(v->back.run());b.addView(arrow,new LinearLayout.LayoutParams(dp(48),dp(64)));TextView t=text(title,22,TEXT);t.setGravity(Gravity.CENTER_VERTICAL);t.setPadding(dp(4),dp(8),0,dp(8));t.setMinHeight(dp(64));b.addView(t,new LinearLayout.LayoutParams(0,-2,1));return b;}
    private void handleBack(){if(subScreen)showSettings();else finish();}
    // API 33+ is handled by OnBackInvokedDispatcher registered in onCreate.
    @SuppressLint("GestureBackNavigation")
    @SuppressWarnings("deprecation")
    @Override public void onBackPressed(){handleBack();}

    private void openClock(){Intent i=getPackageManager().getLaunchIntentForPackage("com.sec.android.app.clockpackage");if(i!=null)startActivity(i);else Toast.makeText(this,R.string.clock_not_found,Toast.LENGTH_LONG).show();}
    private String alignmentName(){return getResources().getStringArray(R.array.alignment_names)[settings.integer(WidgetSettings.KEY_ALIGNMENT,1)];}
    private String timeFormatLabel(){int x=settings.integer(WidgetSettings.KEY_TIME_FORMAT,2);return new SimpleDateFormat(new String[]{"h:mm","h:mm a","HH:mm"}[x],Locale.getDefault()).format(new Date());}
    private String timezoneLabel(){String z=settings.string(WidgetSettings.KEY_TIMEZONE,"auto");return "auto".equals(z)?getString(R.string.automatic):z.substring(z.lastIndexOf('/')+1).replace('_',' ');}
    private String clickAppLabel(){String p=settings.string(WidgetSettings.KEY_CLICK_PACKAGE,"com.sec.android.app.clockpackage");if(p.isEmpty())return getString(R.string.do_nothing);try{return getPackageManager().getApplicationLabel(getPackageManager().getApplicationInfo(p,0)).toString();}catch(Exception e){return p;}}

    private boolean hasDumpPermission(){return checkSelfPermission("android.permission.DUMP")==PackageManager.PERMISSION_GRANTED;}
    private boolean hasUsagePermission(){if(checkSelfPermission("android.permission.PACKAGE_USAGE_STATS")==PackageManager.PERMISSION_GRANTED)return true;AppOpsManager ops=(AppOpsManager)getSystemService(APP_OPS_SERVICE);return ops!=null&&ops.checkOpNoThrow(AppOpsManager.OPSTR_GET_USAGE_STATS,Process.myUid(),getPackageName())==AppOpsManager.MODE_ALLOWED;}
    private boolean hasRequiredPermissions(){return hasDumpPermission()&&hasUsagePermission();}
    private String permissionStatusText(){String yes=getString(R.string.permission_granted),no=getString(R.string.permission_not_granted);return getString(R.string.permission_status_line,getString(R.string.permission_dump_name),hasDumpPermission()?yes:no)+"\n"+getString(R.string.permission_status_line,getString(R.string.permission_usage_name),hasUsagePermission()?yes:no);}
    private void showPermissionStatus(){AlertDialog.Builder builder=new AlertDialog.Builder(this).setTitle(R.string.permission_status_title).setMessage(permissionStatusText()).setPositiveButton(R.string.close,null);if(!hasRequiredPermissions())builder.setNeutralButton(R.string.open_adb_instructions,(d,w)->showPermissionInstructions());builder.show();}
    private void showPermissionInstructions(){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(24),dp(8),dp(24),0);TextView intro=text(getString(R.string.permission_instructions_intro),15,TEXT);intro.setLineSpacing(dp(3),1f);box.addView(intro);TextView commands=text(getString(R.string.permission_commands),13,0xFFFFFFFF);commands.setTypeface(Typeface.MONOSPACE);commands.setTextIsSelectable(true);commands.setHorizontallyScrolling(true);commands.setPadding(0,dp(16),dp(12),dp(16));HorizontalScrollView commandScroll=new HorizontalScrollView(this);commandScroll.setFillViewport(true);commandScroll.setHorizontalScrollBarEnabled(true);commandScroll.setContentDescription(getString(R.string.permission_commands));commandScroll.addView(commands,new HorizontalScrollView.LayoutParams(-2,-2));box.addView(commandScroll,new LinearLayout.LayoutParams(-1,-2));TextView after=text(getString(R.string.permission_instructions_after),14,SUB);after.setLineSpacing(dp(3),1f);box.addView(after);AlertDialog dialog=new AlertDialog.Builder(this).setTitle(R.string.permission_instructions_title).setView(box).setPositiveButton(R.string.close,null).setNeutralButton(R.string.copy_commands,(d,w)->copyPermissionCommands()).create();dialog.show();}
    private void copyPermissionCommands(){ClipboardManager clipboard=(ClipboardManager)getSystemService(CLIPBOARD_SERVICE);if(clipboard!=null){clipboard.setPrimaryClip(ClipData.newPlainText(getString(R.string.permission_instructions_title),getString(R.string.permission_commands)));Toast.makeText(this,R.string.commands_copied,Toast.LENGTH_SHORT).show();}}

    private void showAbout(){subScreen=true;LinearLayout root=screenRoot();root.addView(toolbar(getString(R.string.about_title),this::showSettings));ScrollView scroll=new ScrollView(this);LinearLayout body=vertical(Color.TRANSPARENT);body.setPadding(dp(20),dp(8),dp(20),dp(32));body.addView(aboutText(getString(R.string.app_name),22,TEXT,true));body.addView(aboutText(getString(R.string.version_label,BuildConfig.VERSION_NAME),16,SUB,false));body.addView(aboutText(getString(R.string.developer_label)+": "+getString(R.string.developer_name),16,SUB,false));body.addView(aboutLink(getString(R.string.repository),getString(R.string.repository_summary),getString(R.string.repository_url)));body.addView(aboutLink(getString(R.string.project_license),getString(R.string.project_license_summary),getString(R.string.apache_license_url)));body.addView(aboutLink(getString(R.string.third_party_licenses),getString(R.string.third_party_summary),getString(R.string.repository_url)+"/blob/main/THIRD_PARTY_NOTICES.md"));TextView notice=aboutText(getString(R.string.independent_project_notice),14,SUB,false);notice.setPadding(0,dp(24),0,0);body.addView(notice);scroll.addView(body);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);}
    private TextView aboutText(String value,float size,int color,boolean bold){TextView view=text(value,size,color);view.setLineSpacing(dp(3),1.1f);view.setPadding(0,dp(8),0,dp(8));if(bold)view.setTypeface(Typeface.DEFAULT_BOLD);return view;}
    private View aboutLink(String title,String summary,String url){LinearLayout row=baseRow(title,summary,R.drawable.ic_outline_info);row.setPadding(0,dp(12),0,dp(12));row.setClickable(true);row.setFocusable(true);row.setOnClickListener(v->openUrl(url));return row;}
    private void openUrl(String url){try{startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(url)));}catch(ActivityNotFoundException e){Toast.makeText(this,R.string.open_link_failed,Toast.LENGTH_LONG).show();}}
    private Typeface fontFace(String n){if(n.equals("Light"))return Typeface.create("sans-serif-light",Typeface.NORMAL);if(n.equals("Medium"))return Typeface.create("sans-serif-medium",Typeface.NORMAL);if(n.equals("Condensed"))return Typeface.create("sans-serif-condensed",Typeface.NORMAL);if(n.equals("Classic"))return Typeface.SERIF;return Typeface.create("sans-serif",Typeface.NORMAL);}
    private void rememberSettingsScroll(){if(settingsScroll!=null)settingsScrollY=settingsScroll.getScrollY();}
    private void changed(){changed(false);}
    private void changed(boolean refreshAlarm){alarmMillis=settings.bool(WidgetSettings.KEY_SHOW_ALARM,true)?new AlarmStateCache(this).get():null;refreshPreview();AlarmWidgetProvider.requestUpdate(getApplicationContext(),refreshAlarm);}
    private void refreshPreview(){if(preview==null)return;Bitmap next=WidgetRenderer.render(this,214,84,alarmMillis);Bitmap previous=previewBitmap;previewBitmap=next;preview.setImageBitmap(next);if(previous!=null&&previous!=next&&!previous.isRecycled())previous.recycle();}
    private LinearLayout vertical(int color){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setBackgroundColor(color);return l;}
    private TextView text(String s,float size,int color){TextView v=new TextView(this);v.setText(s);v.setTextSize(size);v.setTextColor(color);return v;}
    private GradientDrawable round(int color,int radius){GradientDrawable g=new GradientDrawable();g.setColor(color);g.setCornerRadius(dp(radius));return g;}
    private int dp(int x){return Math.round(x*getResources().getDisplayMetrics().density);}
    static final class Zone{final String id,name,offset;Zone(String i,String n,String o){id=i;name=n;offset=o;}}
}
